"""
Trace Server for LangChain MCP Agent Execution Visualizations

This module provides a web server to browse and view execution trace files
generated by the LangChain MCP Agent.
"""
import os
import json
import asyncio
import logging
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Any, Optional

from fastapi import FastAPI, Request, HTTPException
from fastapi.responses import HTMLResponse, FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

logger = logging.getLogger(__name__)


class TraceServer:
    """
    Web server for browsing and viewing LangChain MCP Agent execution traces.
    """
    
    def __init__(self, traces_dir: str = "visualizations", port: int = 8090):
        self.traces_dir = Path(traces_dir)
        self.port = port
        self.app = FastAPI(title="LangChain MCP Agent Trace Viewer")
        self._setup_routes()
        
    def _setup_routes(self):
        """Setup FastAPI routes."""
        
        @self.app.get("/", response_class=HTMLResponse)
        async def trace_list(request: Request):
            """Main page showing list of all trace files."""
            traces = self._get_trace_files()
            return self._render_trace_list(traces)
        
        @self.app.get("/trace/{trace_id}")
        async def view_trace(trace_id: str):
            """View a specific trace file."""
            trace_file = self.traces_dir / f"{trace_id}.html"
            if not trace_file.exists():
                raise HTTPException(status_code=404, detail="Trace not found")
            
            # Read and return the HTML content
            with open(trace_file, 'r') as f:
                content = f.read()
            return HTMLResponse(content=content)
        
        @self.app.get("/api/traces")
        async def get_traces():
            """API endpoint to get list of traces as JSON."""
            traces = self._get_trace_files()
            return JSONResponse(traces)
        
        @self.app.get("/api/trace/{trace_id}/data")
        async def get_trace_data(trace_id: str):
            """Get trace data as JSON."""
            json_file = self.traces_dir / f"{trace_id}.json"
            if not json_file.exists():
                raise HTTPException(status_code=404, detail="Trace data not found")
            
            with open(json_file, 'r') as f:
                data = json.load(f)
            return JSONResponse(data)
        
        @self.app.delete("/api/traces")
        async def delete_all_traces():
            """Delete all trace files."""
            try:
                deleted_count = 0
                
                if self.traces_dir.exists():
                    # Delete all JSON trace files
                    for json_file in self.traces_dir.glob("execution_trace_*.json"):
                        try:
                            json_file.unlink()
                            deleted_count += 1
                            logger.info(f"Deleted trace file: {json_file}")
                        except Exception as e:
                            logger.error(f"Error deleting {json_file}: {e}")
                    
                    # Delete corresponding HTML files
                    for html_file in self.traces_dir.glob("execution_trace_*.html"):
                        try:
                            html_file.unlink()
                            logger.info(f"Deleted HTML file: {html_file}")
                        except Exception as e:
                            logger.error(f"Error deleting {html_file}: {e}")
                
                return JSONResponse({
                    "success": True,
                    "deleted_count": deleted_count,
                    "message": f"Deleted {deleted_count} trace files"
                })
                
            except Exception as e:
                logger.error(f"Error deleting traces: {e}")
                raise HTTPException(status_code=500, detail=f"Error deleting traces: {str(e)}")    

    def _get_trace_files(self) -> List[Dict[str, Any]]:
        """Get list of all trace files with metadata."""
        traces = []
        
        if not self.traces_dir.exists():
            return traces
        
        # Find all JSON trace files
        for json_file in self.traces_dir.glob("execution_trace_*.json"):
            try:
                with open(json_file, 'r') as f:
                    data = json.load(f)
                
                # Extract trace ID from filename
                trace_id = json_file.stem
                
                # Check if corresponding HTML file exists
                html_file = self.traces_dir / f"{trace_id}.html"
                has_html = html_file.exists()
                
                traces.append({
                    "id": trace_id,
                    "session_id": data.get("session_id", "unknown"),
                    "start_time": data.get("start_time", ""),
                    "total_steps": data.get("total_steps", 0),
                    "total_duration_ms": data.get("total_duration_ms", 0),
                    "file_size": json_file.stat().st_size,
                    "created_at": datetime.fromtimestamp(json_file.stat().st_mtime).isoformat(),
                    "has_html": has_html
                })
            except Exception as e:
                logger.warning(f"Error reading trace file {json_file}: {e}")
                continue
        
        # Sort by creation time, newest first
        traces.sort(key=lambda x: x["created_at"], reverse=True)
        return traces
    
    def _render_trace_list(self, traces: List[Dict[str, Any]]) -> str:
        """Render the trace list HTML page."""
        html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LangChain MCP Agent Trace Viewer</title>
    <style>
        * {{ box-sizing: border-box; }}
        body {{ 
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
            margin: 0; 
            padding: 24px; 
            background: #fafbfc;
            color: #24292e;
        }}
        .container {{ 
            max-width: 1200px; 
            margin: 0 auto; 
            background: #ffffff; 
            border: 1px solid #e1e4e8;
            border-radius: 6px; 
            box-shadow: 0 1px 3px rgba(27,31,35,0.12);
        }}
        .header {{
            padding: 24px 32px;
            border-bottom: 1px solid #e1e4e8;
            background: #f6f8fa;
        }}
        h1 {{ 
            color: #24292e; 
            margin: 0 0 8px 0;
            font-size: 24px;
            font-weight: 600;
        }}
        .subtitle {{
            color: #586069;
            font-size: 14px;
            margin: 0;
        }}
        .trace-list {{
            padding: 0;
        }}
        .trace-item {{
            display: flex;
            align-items: center;
            padding: 16px 32px;
            border-bottom: 1px solid #f0f3f6;
            transition: background-color 0.15s ease;
            text-decoration: none;
            color: inherit;
        }}
        .trace-item:hover {{
            background-color: #f6f8fa;
        }}
        .trace-item:last-child {{
            border-bottom: none;
        }}
        .trace-info {{
            flex: 1;
        }}
        .trace-title {{
            font-weight: 600;
            color: #24292e;
            margin-bottom: 4px;
            font-size: 14px;
        }}
        .trace-meta {{
            color: #656d76;
            font-size: 12px;
            display: flex;
            gap: 16px;
        }}
        .trace-stats {{
            display: flex;
            gap: 16px;
            align-items: center;
            color: #656d76;
            font-size: 12px;
        }}
        .stat-badge {{
            background: #f6f8fa;
            padding: 2px 6px;
            border-radius: 3px;
            border: 1px solid #d0d7de;
        }}
        .empty-state {{
            text-align: center;
            padding: 64px 32px;
            color: #656d76;
        }}
        .header-actions {{
            display: inline-block;
            margin-left: 16px;
        }}
        .refresh-btn {{
            background: #0969da;
            color: white;
            border: none;
            padding: 6px 12px;
            border-radius: 6px;
            cursor: pointer;
            font-size: 12px;
            margin-right: 8px;
        }}
        .refresh-btn:hover {{
            background: #0860ca;
        }}
        .delete-all-btn {{
            background: #cf222e;
            color: white;
            border: none;
            padding: 6px 12px;
            border-radius: 6px;
            cursor: pointer;
            font-size: 12px;
        }}
        .delete-all-btn:hover {{
            background: #a40e26;
        }}
        .delete-all-btn:disabled {{
            background: #8c959f;
            cursor: not-allowed;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>LangChain MCP Agent Trace Viewer</h1>
            <div class="subtitle">
                Browse and view execution traces from your LangChain MCP Agent
                <div class="header-actions">
                    <button class="refresh-btn" onclick="location.reload()">Refresh</button>
                    <button class="delete-all-btn" onclick="deleteAllTraces()">Delete All</button>
                </div>
            </div>
        </div>
        
        <div class="trace-list">
"""
        
        if not traces:
            html += """
            <div class="empty-state">
                <h3>No traces found</h3>
                <p>Execute some conversations with your LangChain MCP Agent to generate traces.</p>
                <p>Traces are saved in the <code>visualizations/</code> directory.</p>
            </div>
"""
        else:
            for trace in traces:
                duration_sec = trace["total_duration_ms"] / 1000 if trace["total_duration_ms"] else 0
                file_size_kb = trace["file_size"] / 1024
                created_time = datetime.fromisoformat(trace["created_at"]).strftime("%Y-%m-%d %H:%M:%S")
                
                html_badge = '<span class="stat-badge">HTML</span>' if trace['has_html'] else ""
                html += f"""
            <a href="/trace/{trace['id']}" class="trace-item">
                <div class="trace-info">
                    <div class="trace-title">Session: {trace['session_id']}</div>
                    <div class="trace-meta">
                        <span>Created: {created_time}</span>
                        <span>Duration: {duration_sec:.1f}s</span>
                        <span>Steps: {trace['total_steps']}</span>
                    </div>
                </div>
                <div class="trace-stats">
                    <span class="stat-badge">{file_size_kb:.1f} KB</span>
                    {html_badge}
                </div>
            </a>
"""
        
        html += """
        </div>
    </div>
    
    <script>
        async function deleteAllTraces() {
            console.log('Delete All button clicked');
            if (!confirm('Are you sure you want to delete ALL trace files? This action cannot be undone.')) {
                console.log('User cancelled deletion');
                return;
            }
            console.log('User confirmed deletion');
            
            const deleteBtn = document.querySelector('.delete-all-btn');
            const originalText = deleteBtn.textContent;
            
            try {
                deleteBtn.disabled = true;
                deleteBtn.textContent = 'Deleting...';
                
                const response = await fetch('/api/traces', {
                    method: 'DELETE'
                });
                
                if (response.ok) {
                    const result = await response.json();
                    alert('Successfully deleted ' + result.deleted_count + ' trace files.');
                    location.reload(); // Refresh the page to show empty state
                } else {
                    const error = await response.text();
                    alert('Error deleting traces: ' + error);
                }
            } catch (error) {
                alert('Error deleting traces: ' + error.message);
            } finally {
                deleteBtn.disabled = false;
                deleteBtn.textContent = originalText;
            }
        }
    </script>
</body>
</html>
"""
        return html
    
    async def start_server(self):
        """Start the trace server."""
        import uvicorn
        logger.info(f"Starting trace server on http://localhost:{self.port}")
        config = uvicorn.Config(
            app=self.app,
            host="0.0.0.0",
            port=self.port,
            log_level="info"
        )
        server = uvicorn.Server(config)
        await server.serve()


# Standalone server runner
async def run_trace_server(traces_dir: str = "visualizations", port: int = 8090):
    """Run the trace server as a standalone application."""
    server = TraceServer(traces_dir, port)
    await server.start_server()


if __name__ == "__main__":
    import sys
    
    traces_dir = sys.argv[1] if len(sys.argv) > 1 else "visualizations"
    port = int(sys.argv[2]) if len(sys.argv) > 2 else 8090
    
    print(f"🚀 Starting LangChain MCP Agent Trace Server")
    print(f"📁 Traces directory: {traces_dir}")
    print(f"🌐 Server URL: http://localhost:{port}")
    print(f"📊 Browse your execution traces in the web interface")
    
    asyncio.run(run_trace_server(traces_dir, port))