# Branch Protection Rules for Master Branch
# This file documents the recommended branch protection settings
# To apply these settings, go to Settings > Branches > Add rule

branch_protection:
  branch_name: "master"
  
  # Require pull request reviews before merging
  require_pull_request_reviews: true
  required_approving_review_count: 1
  dismiss_stale_reviews: true
  require_code_owner_reviews: false
  
  # Require status checks to pass before merging
  require_status_checks: true
  required_status_checks:
    - "build-and-deploy"
    - "test"
  
  # Require branches to be up to date before merging
  require_branches_to_be_up_to_date: true
  
  # Restrict pushes that create files that use the gitfile: protocol
  restrict_pushes: false
  
  # Allow force pushes
  allow_force_pushes: false
  
  # Allow deletions
  allow_deletions: false
  
  # Require linear history
  require_linear_history: false
  
  # Lock branch
  lock_branch: false
  
  # Allow bypass of the above settings
  allow_bypass_pull_request_allowances: false
  
  # Include administrators
  enforce_admins: true
  
  # Restrict who can push to matching branches
  restrictions:
    users: []
    teams: []
    apps: []

# Additional recommended settings:
# - Enable "Require conversation resolution before merging"
# - Enable "Require signed commits"
# - Enable "Require deployments to succeed before merging"
# - Set up required status checks for CI/CD pipelines 