/**
 * @file src/icons/index.ts
 * @description Validated react-icons/fi barrel — single source of truth for all icons.
 *
 * ALL icon imports must come through here — never import directly from 'react-icons/fi'.
 * Any invented or misspelled icon name will be a TypeScript compile error.
 *
 * To add a new icon:
 *   1. Verify it exists at https://feathericons.com
 *   2. Add the name to this export list
 *   3. Run `npm run icons:check` to validate
 *
 * Run `npm run icons:check` to catch any invalid imports across the codebase.
 * Run `npm run icons:fix`  to rewrite all direct react-icons/fi imports to @icons.
 */

export {
  FiActivity,
  FiAlertCircle,
  FiAlertOctagon,
  FiAlertTriangle,
  FiArrowDown,
  FiArrowLeft,
  FiArrowRight,
  FiAward,
  FiBarChart,
  FiBarChart2,
  FiBattery,
  FiBell,
  FiBellOff,
  FiBook,
  FiBookOpen,
  FiBookmark,
  FiBox,
  FiBriefcase,
  FiCalendar,
  FiCamera,
  FiCheck,
  FiCheckCircle,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiChevronUp,
  FiChevronsLeft,
  FiChevronsRight,
  FiClock,
  FiCloud,
  FiCloudOff,
  FiCode,
  FiCompass,
  FiCopy,
  FiCpu,
  FiCreditCard,
  FiDatabase,
  FiDollarSign,
  FiDownload,
  FiEdit,
  FiEdit2,
  FiEdit3,
  FiExternalLink,
  FiEye,
  FiEyeOff,
  FiFacebook,
  FiFile,
  FiFileText,
  FiFilter,
  FiFlag,
  FiFolder,
  FiGitBranch,
  FiGitMerge,
  FiGithub,
  FiGlobe,
  FiGrid,
  FiHardDrive,
  FiHash,
  FiHeart,
  FiHelpCircle,
  FiHome,
  FiImage,
  FiInbox,
  FiInfo,
  FiInstagram,
  FiKey,
  FiLayers,
  FiLayout,
  FiLink,
  FiLink2,
  FiLinkedin,
  FiList,
  FiLoader,
  FiLock,
  FiLogIn,
  FiLogOut,
  FiMail,
  FiMapPin,
  FiMaximize,
  FiMaximize2,
  FiMenu,
  FiMessageCircle,
  FiMessageSquare,
  FiMic,
  FiMinimize,
  FiMinimize2,
  FiMinus,
  FiMonitor,
  FiMoon,
  FiMoreHorizontal,
  FiMoreVertical,
  FiMove,
  FiMusic,
  FiNavigation,
  FiPackage,
  FiPaperclip,
  FiPause,
  FiPhone,
  FiPhoneCall,
  FiPieChart,
  FiPlay,
  FiPlus,
  FiPrinter,
  FiRefreshCw,
  FiRepeat,
  FiRotateCcw,
  FiRotateCw,
  FiSave,
  FiSearch,
  FiSend,
  FiServer,
  FiSettings,
  FiShare,
  FiShare2,
  FiShield,
  FiShoppingCart,
  FiShuffle,
  FiSkipBack,
  FiSkipForward,
  FiSlash,
  FiSmartphone,
  FiSmile,
  FiSpeaker,
  FiStar,
  FiSun,
  FiTable,
  FiTablet,
  FiTag,
  FiTarget,
  FiTerminal,
  FiToggleLeft,
  FiToggleRight,
  FiTool,
  FiTrash,
  FiTrash2,
  FiTrendingDown,
  FiTrendingUp,
  FiTruck,
  FiTv,
  FiTwitter,
  FiUnlock,
  FiUpload,
  FiUser,
  FiUserCheck,
  FiUsers,
  FiVideo,
  FiVolume,
  FiVolume2,
  FiVolumeX,
  FiWifi,
  FiWifiOff,
  FiX,
  FiXCircle,
  FiYoutube,
  FiZap,
} from 'react-icons/fi';

// ── Aliases ───────────────────────────────────────────────────────────────────
// Kept for backwards compatibility with existing JSX. Do not add new aliases.
// New code should use the canonical Fi* name directly.
export { FiLock as FiLockIcon } from 'react-icons/fi';
