import {
	FiActivity,
	FiAlertCircle,
	FiAlertOctagon,
	FiAlertTriangle,
	FiArrowDown,
	FiArrowLeft,
	FiArrowRight,
	FiAward,
	FiBarChart,
	FiBarChart2,
	FiBattery,
	FiBell,
	FiBook,
	FiBookmark,
	FiBookOpen,
	FiBox,
	FiCalendar,
	FiCamera,
	FiCheck,
	FiCheckCircle,
	FiChevronDown,
	FiChevronLeft,
	FiChevronRight,
	FiChevronsLeft,
	FiChevronsRight,
	FiChevronUp,
	FiClock,
	FiCloud,
	FiCloudOff,
	FiCode,
	FiCopy,
	FiCpu,
	FiCreditCard,
	FiDatabase,
	FiDollarSign,
	FiDownload,
	FiEdit,
	FiEdit3,
	FiExternalLink,
	FiEye,
	FiEyeOff,
	FiFile,
	FiFileText,
	FiFilter,
	FiFolder,
	FiGitBranch,
	FiGithub,
	FiGlobe,
	FiGrid,
	FiHash,
	FiHeart,
	FiHelpCircle,
	FiHome,
	FiImage,
	FiInfo,
	FiKey,
	FiLayers,
	FiLayout,
	FiLink,
	FiLink2,
	FiList,
	FiLoader,
	FiLock,
	FiLogIn,
	FiLogOut,
	FiMail,
	FiMapPin,
	FiMaximize,
	FiMaximize2,
	FiMenu,
	FiMessageCircle,
	FiMessageSquare,
	FiMic,
	FiMinimize,
	FiMinimize2,
	FiMinus,
	FiMonitor,
	FiMoon,
	FiMoreHorizontal,
	FiMoreVertical,
	FiMove,
	FiMusic,
	FiNavigation,
	FiPackage,
	FiPaperclip,
	FiPause,
	FiPhone,
	FiPhoneCall,
	FiPieChart,
	FiPlay,
	FiPlus,
	FiPrinter,
	FiRefreshCw,
	FiRepeat,
	FiRotateCcw,
	FiRotateCw,
	FiSave,
	FiSearch,
	FiSend,
	FiServer,
	FiSettings,
	FiShare,
	FiShare2,
	FiShield,
	FiShoppingCart,
	FiShuffle,
	FiSkipBack,
	FiSkipForward,
	FiSlash,
	FiSmartphone,
	FiSpeaker,
	FiStar,
	FiSun,
	FiTable,
	FiTablet,
	FiTag,
	FiTarget,
	FiTerminal,
	FiToggleLeft,
	FiToggleRight,
	FiTool,
	FiTrash,
	FiTrash2,
	FiTrendingDown,
	FiTrendingUp,
	FiTruck,
	FiTv,
	FiUnlock,
	FiUpload,
	FiUser,
	FiUsers,
	FiVideo,
	FiVolume,
	FiVolume2,
	FiVolumeX,
	FiWifi,
	FiWifiOff,
	FiX,
	FiXCircle,
	FiZap,
} from 'react-icons/fi';
import { useNavigate } from 'react-router-dom';
import styled from 'styled-components';
import ClientAuthMethodSelector from '../components/ClientAuthMethodSelector';
import ComprehensiveDiscoveryInput from '../components/ComprehensiveDiscoveryInput';
import { ConfigCheckerButtons } from '../components/ConfigCheckerButtons';
import { CredentialsInput } from '../components/CredentialsInput';
import { DraggableModal } from '../components/DraggableModal';
import type { StepCredentials } from '../components/steps/CommonSteps';
import { WorkerTokenDetectedBanner } from '../components/WorkerTokenDetectedBanner';
import { WorkerTokenModal } from '../components/WorkerTokenModal';
import type { ClientAuthMethod } from '../utils/clientAuthentication';
import { trackedFetch } from '../utils/trackedFetch';
import { v4ToastManager } from '../utils/v4ToastMessages';
import type { CodeDisplayProps, SupportedLanguage } from './codeHighlightingService';
import {
	formatAndHighlightJSON,
	getVSCodeStyles,
	highlightCode,
	VSCODE_COLORS,
} from './codeHighlightingService';
import { CollapsibleHeader } from './collapsibleHeaderService';
import ComprehensiveCredentialsService, {
	getAllowedResponseTypes,
	getFlowAuthMethods,
	getFlowGrantTypes,
	getFlowResponseTypes,
} from './comprehensiveCredentialsService';
import {
	comprehensiveDiscoveryService,
	type DiscoveryResult,
} from './comprehensiveDiscoveryService';
import { config } from './config';
import credentialsValidationService from './credentialsValidationService';
import { environmentIdPersistenceService } from './environmentIdPersistenceService';
import flowConfigService from './flowConfigService';
import flowCredentialService from './flowCredentialService';
import { getDefaultScopesForFlow } from './flowScopeMappingService';
import flowStateService from './flowStateService';
import { oidcDiscoveryService } from './oidcDiscoveryService';
import type { PingOneApplication } from './pingOneApplicationService';
import { showTokenSuccessMessage } from './tokenExpirationService';
import type { WorkerTokenCredentials } from './workerTokenCredentialsService';
import workerTokenCredentialsService from './workerTokenCredentialsService';

export {
	FiActivity,
	FiAlertCircle,
	FiAlertOctagon,
	FiAlertTriangle,
	FiArrowDown,
	FiArrowLeft,
	FiArrowRight,
	FiAward,
	FiBarChart,
	FiBarChart2,
	FiBattery,
	FiBell,
	FiBook,
	FiBookmark,
	FiBookOpen,
	FiBox,
	FiCalendar,
	FiCamera,
	FiCheck,
	FiCheckCircle,
	FiChevronDown,
	FiChevronLeft,
	FiChevronRight,
	FiChevronUp,
	FiChevronsLeft,
	FiChevronsRight,
	FiClock,
	FiCloud,
	FiCloudOff,
	FiCode,
	FiCopy,
	FiCpu,
	FiCreditCard,
	FiDatabase,
	FiDollarSign,
	FiDownload,
	FiEdit,
	FiEdit3,
	FiExternalLink,
	FiEye,
	FiEyeOff,
	FiFile,
	FiFileText,
	FiFilter,
	FiFolder,
	FiGitBranch,
	FiGithub,
	FiGlobe,
	FiGrid,
	FiHash,
	FiHeart,
	FiHelpCircle,
	FiHome,
	FiImage,
	FiInfo,
	FiKey,
	FiLayers,
	FiLayout,
	FiLink,
	FiLink2,
	FiList,
	FiLoader,
	FiLock,
	FiLogIn,
	FiLogOut,
	FiMail,
	FiMapPin,
	FiMaximize,
	FiMaximize2,
	FiMenu,
	FiMessageCircle,
	FiMessageSquare,
	FiMic,
	FiMinimize,
	FiMinimize2,
	FiMinus,
	FiMonitor,
	FiMoon,
	FiMoreHorizontal,
	FiMoreVertical,
	FiMove,
	FiMusic,
	FiNavigation,
	FiPackage,
	FiPaperclip,
	FiPause,
	FiPhone,
	FiPhoneCall,
	FiPieChart,
	FiPlay,
	FiPlus,
	FiPrinter,
	FiRefreshCw,
	FiRepeat,
	FiRotateCcw,
	FiRotateCw,
	FiSave,
	FiSearch,
	FiSend,
	FiServer,
	FiSettings,
	FiShare,
	FiShare2,
	FiShield,
	FiShoppingCart,
	FiShuffle,
	FiSkipBack,
	FiSkipForward,
	FiSlash,
	FiSmartphone,
	FiSpeaker,
	FiStar,
	FiSun,
	FiTable,
	FiTablet,
	FiTag,
	FiTarget,
	FiTerminal,
	FiToggleLeft,
	FiToggleRight,
	FiTool,
	FiTrash,
	FiTrash2,
	FiTrendingDown,
	FiTrendingUp,
	FiTruck,
	FiTv,
	FiUnlock,
	FiUpload,
	FiUser,
	FiUsers,
	FiVideo,
	FiVolume,
	FiVolume2,
	FiVolumeX,
	FiWifi,
	FiWifiOff,
	FiX,
	FiXCircle,
	FiZap,
};

export { styled, useNavigate };

export {
	ComprehensiveCredentialsService,
	flowConfigService,
	flowCredentialService,
	flowStateService,
	credentialsValidationService,
	environmentIdPersistenceService,
	oidcDiscoveryService,
	workerTokenCredentialsService,
	v4ToastManager,
	comprehensiveDiscoveryService,
};

export {
	WorkerTokenModal,
	WorkerTokenDetectedBanner,
	CredentialsInput,
	ClientAuthMethodSelector,
	ComprehensiveDiscoveryInput,
	ConfigCheckerButtons,
	CollapsibleHeader,
	DraggableModal,
};

export type {
	ClientAuthMethod,
	CodeDisplayProps,
	DiscoveryResult,
	PingOneApplication,
	StepCredentials,
	SupportedLanguage,
	WorkerTokenCredentials,
};

export {
	trackedFetch,
	config,
	getDefaultScopesForFlow,
	showTokenSuccessMessage,
	VSCODE_COLORS,
	formatAndHighlightJSON,
	getVSCodeStyles,
	highlightCode,
};

export { getAllowedResponseTypes, getFlowAuthMethods, getFlowGrantTypes, getFlowResponseTypes };
