#!/bin/bash

# Worker Token Consistency Analysis
# Analyzes all places where worker tokens are saved/created for consistency

echo "🔑 Worker Token Consistency Analysis"
echo "=================================="

echo ""
echo "📊 Usage Statistics:"
echo "- Worker token save operations: $(find src -name "*.ts" -o -name "*.tsx" | xargs grep -c "saveToken\|save.*token" | awk -F: '{sum += $2} END {print sum}')"
echo "- Files with worker token operations: $(find src -name "*.ts" -o -name "*.tsx" | xargs grep -l "workerToken" | wc -l)"

echo ""
echo "🏗️ Architecture Overview:"
echo ""
echo "1. unifiedWorkerTokenServiceV2.ts (PRIMARY)"
echo "   - Main service for worker token management"
echo "   - Uses workerTokenRepository for storage"
echo "   - Broadcasts events for updates"
echo "   - Handles credentials and tokens"
echo ""
echo "2. workerTokenServiceV8.ts (WRAPPER)"
echo "   - V8-specific wrapper around unified service"
echo "   - Provides backward compatibility"
echo "   - Delegates to unifiedWorkerTokenService"
echo ""
echo "3. workerTokenRepository.ts (STORAGE)"
echo "   - Low-level storage operations"
echo "   - Uses unifiedStorageManager"
echo "   - Handles persistence"
echo ""
echo "4. workerTokenCacheServiceV8.ts (CACHING)"
echo "   - Pre-flight validation caching"
echo "   - Performance optimization"
echo "   - Separate from main storage"

echo ""
echo "🔄 Save Operation Patterns:"
echo ""
echo "✅ CONSISTENT - Primary Pattern:"
echo "   await unifiedWorkerTokenService.saveToken(token, expiresAt);"
echo "   Used in: WorkerTokenModalV8.tsx, workerTokenServiceV8.ts"
echo ""
echo "✅ CONSISTENT - V8 Wrapper Pattern:"
echo "   await workerTokenServiceV8.saveToken(token, expiresAt);"
echo "   Used in: mfaAuthenticationServiceV8.ts, appDiscoveryServiceV8.ts"
echo ""
echo "⚠️  LEGACY - Direct localStorage Pattern:"
echo "   localStorage.setItem('worker_token', token);"
echo "   Found in: saveButtonService.tsx (should be migrated)"
echo ""
echo "✅ CONSISTENT - Credentials First Pattern:"
echo "   await unifiedWorkerTokenService.saveCredentials(credentials);"
echo "   await unifiedWorkerTokenService.saveToken(token, expiresAt);"
echo "   Used in: WorkerTokenModalV8.tsx, ClientGenerator.tsx"

echo ""
echo "🔍 Consistency Issues Found:"
echo ""

# Check for direct localStorage usage
echo "1. Direct localStorage Usage:"
find src -name "*.ts" -o -name "*.tsx" | xargs grep "localStorage.*worker.*token\|worker.*token.*localStorage" | head -5

echo ""
echo "2. Mixed Service Usage:"
echo "   Some files use both unifiedWorkerTokenService and workerTokenServiceV8"
echo "   This is actually OK - workerTokenServiceV8 wraps the unified service"

echo ""
echo "3. Event Broadcasting:"
echo "   ✅ unifiedWorkerTokenService broadcasts events"
echo "   ✅ workerTokenServiceV8 delegates to unified service"
echo "   ⚠️  Some direct saves might not broadcast events"

echo ""
echo "📋 Key Files Analysis:"
echo ""

echo "WorkerTokenModalV8.tsx:"
echo "  ✅ Uses unifiedWorkerTokenService.saveCredentials()"
echo "  ✅ Uses unifiedWorkerTokenService.saveToken()"
echo "  ✅ Also saves to environmentService (NEW)"
echo "  ✅ Broadcasts events"
echo ""

echo "workerTokenServiceV8.ts:"
echo "  ✅ Wraps unifiedWorkerTokenService"
echo "  ✅ Consistent delegation"
echo "  ✅ Maintains backward compatibility"
echo ""

echo "mfaAuthenticationServiceV8.ts:"
echo "  ✅ Uses workerTokenServiceV8.saveToken()"
echo "  ✅ Handles token renewal"
echo "  ✅ Dispatches events"
echo ""

echo "appDiscoveryServiceV8.ts:"
echo "  ✅ Uses workerTokenServiceV8.saveToken()"
echo "  ✅ Validates credentials first"
echo "  ✅ Good error handling"
echo ""

echo "saveButtonService.tsx:"
echo "  ⚠️  Uses direct localStorage (LEGACY)"
echo "  ⚠️  Should migrate to unified service"
echo "  ⚠️  No event broadcasting"

echo ""
echo "🎯 Recommendations:"
echo ""
echo "1. ✅ KEEP - Current unifiedWorkerTokenService pattern"
echo "   - It's consistent and well-designed"
echo "   - Event broadcasting works correctly"
echo "   - Storage is centralized"
echo ""
echo "2. 🔄 MIGRATE - Direct localStorage usage"
echo "   - Update saveButtonService.tsx to use unified service"
echo "   - Ensure all saves go through unifiedWorkerTokenService"
echo ""
echo "3. ✅ KEEP - V8 wrapper pattern"
echo "   - workerTokenServiceV8 provides good backward compatibility"
echo "   - Clear delegation to unified service"
echo ""
echo "4. ✅ EXPAND - Environment service integration"
echo "   - More services should save to environmentService"
echo "   - Centralizes environment ID management"
echo ""
echo "5. 📊 MONITOR - Add consistency checks"
echo "   - Runtime validation of token format"
echo "   - Cross-service token validation"
echo "   - Event broadcasting verification"

echo ""
echo "🔍 Overall Assessment: 🟢 MOSTLY CONSISTENT"
echo ""
echo "✅ Good:"
echo "- Primary services use unifiedWorkerTokenService"
echo "- Event broadcasting is consistent"
echo "- V8 wrapper provides good compatibility"
echo "- Credentials-first pattern is followed"
echo ""
echo "⚠️  Needs Attention:"
echo "- Some direct localStorage usage (legacy)"
echo "- Could benefit from more environmentService integration"
echo ""
echo "🎯 Conclusion: The architecture is sound and mostly consistent."
echo "   The unifiedWorkerTokenService is the correct single source of truth."
